### ISSUE TITLE
clang-tools-extra keeps spawning clang and clang-tidy processes indefinitely

### ISSUE THREAD

**Issue by ebroto** [HiroakiMikami/atom-clang-tools-extra#15]
After enabling the plug-in and running Linter:Lint, the plug-in is spawning clang and clang-tidy processes (~64) indefinitely and the linter never stops. I've tried specifying compile_commands.json and also without specifying it. I tried also removing the build directory (we're using out of source builds); the behavior is always the same. Both clang-tidy and clang-rename are in my $PATH

$ uname -a
Linux debian 4.9.0-2-amd64 #1 SMP Debian 4.9.13-1 (2017-02-27) x86_64 GNU/Linux

$ atom --version
Atom    : 1.15.0
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0

$ clang --version
clang version 3.9.1-4 (tags/RELEASE_391/rc2)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin

$ clang-tidy --version
LLVM (http://llvm.org/):
  LLVM version 3.9.1
  
  Optimized build.
  Default target: x86_64-pc-linux-gnu
  Host CPU: skylake

$ clang-rename --version
clang-rename version 0.0.1

$ ps aux | grep tidy
ebroto   17098 14.6  1.6 329348 265960 tty2    R+   10:33   0:10 clang-tidy -export-fixes /tmp/atom-clang-tools-extra-Mon Mar 27 2017 10:33:00 GMT+0200 (CEST) -extra-arg -xc++ -p /home/ebroto/path/to/source/clang-linux-build/compile_commands.json /home/ebroto/path/to/source/some/source/dir/Source.cpp
ebroto   17100 14.6  1.6 329192 265636 tty2    R+   10:33   0:10 clang-tidy -export-fixes /tmp/atom-clang-tools-extra-Mon Mar 27 2017 10:33:00 GMT+0200 (CEST) -extra-arg -xc++ -p /home/ebroto/path/to/source/clang-linux-build/compile_commands.json /home/ebroto/path/to/source/some/source/dir/Source.cpp
ebroto   17103 14.4  1.6 329364 265684 tty2    R+   10:33   0:10 clang-tidy -export-fixes /tmp/atom-clang-tools-extra-Mon Mar 27 2017 10:33:00 GMT+0200 (CEST) -extra-arg -xc++ -p /home/ebroto/path/to/source/clang-linux-build/compile_commands.json /home/ebroto/path/to/source/some/source/dir/Source.cpp
ebroto   17106 14.0  1.6 329204 265764 tty2    R+   10:33   0:10 clang-tidy -export-fixes /tmp/atom-clang-tools-extra-Mon Mar 27 2017 10:33:00 GMT+0200 (CEST) -extra-arg -xc++ -p /home/ebroto/path/to/source/clang-linux-build/compile_commands.json /home/ebroto/path/to/source/some/source/dir/Source.cpp
ebroto   17109 14.3  1.6 329252 265992 tty2    R+   10:33   0:10 clang-tidy -export-fixes /tmp/atom-clang-tools-extra-Mon Mar 27 2017 10:33:01 GMT+0200 (CEST) -extra-arg -xc++ -p /home/ebroto/path/to/source/clang-linux-build/compile_commands.json /home/ebroto/path/to/source/some/source/dir/Source.cpp
ebroto   17112 14.0  1.6 329252 265556 tty2    R+   10:33   0:09 clang-tidy -export-fixes /tmp/atom-clang-tools-extra-Mon Mar 27 2017 10:33:01 GMT+0200 (CEST) -extra-arg -xc++ -p /home/ebroto/path/to/source/clang-linux-build/compile_commands.json /home/ebroto/path/to/source/some/source/dir/Source.cpp
ebroto   17115 13.8  1.6 329360 265552 tty2    R+   10:33   0:09 clang-tidy -export-fixes /tmp/atom-clang-tools-extra-Mon Mar 27 2017 10:33:01 GMT+0200 (CEST) -extra-arg -xc++ -p /home/ebroto/path/to/source/clang-linux-build/compile_commands.json /home/ebroto/path/to/source/some/source/dir/Source.cpp
ebroto   17119 13.3  1.6 329140 265488 tty2    R+   10:33   0:09 clang-tidy -export-fixes /tmp/atom-clang-tools-extra-Mon Mar 27 2017 10:33:01 GMT+0200 (CEST) -extra-arg -xc++ -p /home/ebroto/path/to/source/clang-linux-build/compile_commands.json /home/ebroto/path/to/source/some/source/dir/Source.cpp
ebroto   17121 13.6  1.6 329368 265640 tty2    R+   10:33   0:09 clang-tidy -export-fixes /tmp/atom-clang-tools-extra-Mon Mar 27 2017 10:33:01 GMT+0200 (CEST) -extra-arg -xc++ -p /home/ebroto/path/to/source/clang-linux-build/compile_commands.json /home/ebroto/path/to/source/some/source/dir/Source.cpp
ebroto   17125 13.6  1.6 329208 265624 tty2    R+   10:33   0:09 clang-tidy -export-fixes /tmp/atom-clang-tools-extra-Mon Mar 27 2017 10:33:02 GMT+0200 (CEST) -extra-arg -xc++ -p /home/ebroto/path/to/source/clang-linux-build/compile_commands.json /home/ebroto/path/to/source/some/source/dir/Source.cpp
ebroto   17127 12.2  1.6 320500 256880 tty2    R+   10:33   0:08 clang-tidy -export-fixes /tmp/atom-clang-tools-extra-Mon Mar 27 2017 10:33:02 GMT+0200 (CEST) -extra-arg -xc++ -p /home/ebroto/path/to/source/clang-linux-build/compile_commands.json /home/ebroto/path/to/source/some/source/dir/Source.cpp
ebroto   17130 13.3  1.6 320544 257044 tty2    R+   10:33   0:09 clang-tidy -export-fixes /tmp/atom-clang-tools-extra-Mon Mar 27 2017 10:33:02 GMT+0200 (CEST) -extra-arg -xc++ -p /home/ebroto/path/to/source/clang-linux-build/compile_commands.json /home/ebroto/path/to/source/some/source/dir/Source.cpp
ebroto   17133 12.7  1.6 320496 256816 tty2    R+   10:33   0:08 clang-tidy -export-fixes /tmp/atom-clang-tools-extra-Mon Mar 27 2017 10:33:02 GMT+0200 (CEST) -extra-arg -xc++ -p /home/ebroto/path/to/source/clang-linux-build/compile_commands.json /home/ebroto/path/to/source/some/source/dir/Source.cpp
ebroto   17137 13.3  1.6 320504 257144 tty2    R+   10:33   0:09 clang-tidy -export-fixes /tmp/atom-clang-tools-extra-Mon Mar 27 2017 10:33:03 GMT+0200 (CEST) -extra-arg -xc++ -p /home/ebroto/path/to/source/clang-linux-build/compile_commands.json /home/ebroto/path/to/source/some/source/dir/Source.cpp
[...]

Atom console shows repeatedly the following error after running Linter:Lint:
[Linter] Error running clang Error: Process execution timed out(…)(anonymous function) @ linter-registry.js [sm]:144

I'm using version 0.0.2 of clang-tools-extra.

**Comment by twdkeule** [comment]
I can confirm this in version 0.1.0
